# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b8251b988a730c7aa38671524dd9036fd57ef28bf63c69c679c416edb94cfb7b2ba19d18bb0be8c06382b61345c58299e84b3cef7e91c92ffb8c1fbb6cf9fab

test:
  secret_key_base: 34302ae257849b622f3224e3b2a1ae71132081b5d643fd3a98c08b0d40a56060f93b8fae835d5201175f5119d5a58d72dfe9ad0c8433a2ff28421411ce3cd3e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
